import { Inter,Outfit } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

const outfit=Outfit({
  weight: ['400','500','600'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='dark' lang="en">
      
      <body className={`${outfit.className} bg-background-950 `}><Navbar/>{children}</body>
    </html>
  )
}
